version: '3'

services:

  application:
    container_name: application
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/votedb
      JDBC_USER: postgres
      JDBC_PASSWORD: postgres
      PORT: 8080

  postgres:
    container_name: postgres
    image: postgres:11-alpine
    command: [ "-c", "max_connections=200" ]
    ports:
      - 5432:5432
#    volumes:
#      - ./src/main/resources/db.migration:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votedb