apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: votedb
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: ./src/main/resources/db.migration:/var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}